services:
  db:
    image: postgres:15-alpine
    container_name: odoo_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    build: .
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      DB_NAME: ${DB_NAME}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
      HOST: ${DB_HOST}
      PORT: ${DB_PORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./odoo/addons:/opt/odoo/odoo/addons
      - ./odoo/odoo:/opt/odoo/odoo
      - odoo_data:/var/lib/odoo

volumes:
  db_data:
  odoo_data:

